# Default values for monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      additionalScrapeConfigs:
        - job_name: serviceMonitor/monitoring/monitoring-iracelog-postgres/0
          scrape_interval: 15s
          kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - iracelog
          relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: pod
          - source_labels: [__address__]
            action: replace
            regex: ([^:]+)(?::\d+)?
            replacement: ${1}:9187
            target_label: __address__
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            action: keep
            regex: postgresql
  grafana:
    sidecar.dashboards.enabled: true