namespace: iracelog
resources:
  - namespace.yml
  - deploy-frontend.yml
  - deploy-crossbar.yml
  - service-frontend.yml  
  - service-crossbar.yml  
  - persistentvolume.yml  
  
configMapGenerator:
  - name: frontend-config
    files:
    - config.json=configs/frontend.json
  - name: crossbar-config
    files:
    - config.json=configs/crossbar.json

secretGenerator:
  - name: my-secrets
    envs:
      - .env

# patchesStrategicMerge:
#   - deployment.yml