apiVersion: v1
kind: PersistentVolume
metadata:
  name: iracelog-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  
  accessModes:
    - ReadWriteOnce
  
  storageClassName: hostpath  
  hostPath:
    path: "/mnt/c/tmp/mpdata"
