apiVersion: v1
kind: Service
metadata:
  name: iracelog-crossbar-service
  namespace: iracelog
  labels:
    app: iracelog-crossbar
spec:
  type: LoadBalancer
  selector:
    app: iracelog-crossbar
  ports:
    - protocol: TCP
      name: crossbar
      port: 8094
      targetPort: 8080
    

