{{- if .Values.ingress.traefik.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingress-route
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:        
    - match: Host(`{{ tpl .Values.grafanaDomain . }}`) 
      kind: Rule
      services:
        - name: {{ .Release.Name }}-grafana          
          port: 80 
{{- end -}}          