services:

  db:
    image: postgres:16

    ports:
      - ${DB_PORT:-5432}:5432
    volumes:      
      - db-data:/var/lib/postgresql/data
      - /var/local/dumps:/var/local/dumps
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER_NAME} -d ${DB_SCHEMA}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      TZ: "Europe/Berlin"
      POSTGRES_DB: ${DB_SCHEMA}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    command: "postgres -c shared_buffers=512MB -c work_mem=30MB -c fsync=off"
    networks:
      - somenet

  
  # iracelog-service-manager
  grpc:
    image: ghcr.io/mpapenbr/iracelog-service-manager-go:v0.31.0

    ports:
      - ${GRPC_PORT:-8091}:8080
    networks:
      - somenet
    environment:
      TZ: "Europe/Berlin"
      ISM_ADMIN_TOKEN: ${ISM_ADMIN_TOKEN}
      ISM_PROVIDER_TOKEN: ${ISM_DATAPROVIDER_TOKEN}
      ISM_DATAPROVIDER_TOKEN: ${ISM_DATAPROVIDER_TOKEN}
      ISM_DB: ${DB_URL}
    command: "grpc -a 0.0.0.0:8080"
    depends_on:
      - db
      

  db-migrate:
    image: ghcr.io/mpapenbr/iracelog-service-manager-go:v0.31.0
    networks:
      - somenet
    environment:
      TZ: "Europe/Berlin"      
      ISM_DB: ${DB_URL}
    command: "migrate"

    depends_on:
      db:
        condition: service_healthy
  

  # the frontend
  iracelog:
    image: ghcr.io/mpapenbr/iracelog-web:v0.33.0
    # only used for development
    ports:
      - ${IRACELOG_PORT:-8092}:80
    networks:
      - somenet

    environment:
      TZ: "Europe/Berlin"
    volumes:
      - ./config/iracelog/frontend.json:/usr/share/nginx/html/config.json

  # the graphql api service
  graphql:
    image: ghcr.io/mpapenbr/iracelog-graphql:v0.4.0
    ports:
      - "${GRAPHQL_PORT:-8093}:8080"
    networks:
      - somenet
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: "Europe/Berlin"
      DATABASE_URL: $DB_URL

  main-services:
    image: busybox
    command: sh -c "echo Starting services"
    depends_on:
      - db      
      - db-migrate
      - grpc      
      - iracelog
      - graphql

volumes:
  db-data:
  backup:


networks:
  somenet:
