version: '3.1'

services:

  db:
    image: postgres:15

    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/conf/custom.conf:/custom.conf
      - db-data:/var/lib/postgresql/data
      - /var/local/dumps:/var/local/dumps
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      TZ: "Europe/Berlin"
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      DB_USER_NAME: $DB_USER_NAME
      DB_USER_PASSWORD: $DB_USER_PASSWORD

    networks:
      - somenet

  # iracelog-wamp-router (replacement for crossbar router)
  iwr:
    image: ghcr.io/mpapenbr/iracelog-wamp-router:v0.0.2
    ports:
      - "8091:8080"
    networks:
      - somenet

    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "5"
    #user: "1000:1000"
    # entrypoint: "/iracelog-wamp-router"
    command: "server --logLevel info"
    environment:
      TZ: "Europe/Berlin"
      DATAPROVIDER_TICKET: ${CROSSBAR_DATAPROVIDER_TICKET}
      BACKEND_TICKET: ${CROSSBAR_BACKEND_TICKET}
      ADMIN_TICKET: ${CROSSBAR_ADMIN_TICKET}

  # iracelog-service-manager
  ism:
    image: ghcr.io/mpapenbr/iracelog-service-manager-go:v0.7.0

    networks:
      - somenet
    environment:
      TZ: "Europe/Berlin"
      ISM_URL: ${RACELOG_URL}
      ISM_REALM: ${RACELOG_REALM}
      ISM_USER: ${RACELOG_USER}
      ISM_PASSWORD: ${CROSSBAR_BACKEND_TICKET}
      ISM_DB: ${DB_URL}
    command: "server"
    depends_on:
      - db
      - iwr

  db-migrate:
    image: ghcr.io/mpapenbr/iracelog-service-manager-go:v0.7.0

    networks:
      - somenet

    environment:
      TZ: "Europe/Berlin"
      ISM_URL: ${RACELOG_URL}
      ISM_REALM: ${RACELOG_REALM}
      ISM_USER: ${RACELOG_USER}
      ISM_PASSWORD: ${CROSSBAR_BACKEND_TICKET}
      ISM_DB: ${DB_URL}
    command: "migrate"

    depends_on:
      db:
        condition: service_healthy
      iwr:
        condition: service_started

  # iracelog-analysis-service
  ias:
    image: ghcr.io/mpapenbr/iracelog-analysis-service:v0.3.0
    networks:
      - somenet

    environment:
      TZ: "Europe/Berlin"
      CROSSBAR_URL: ${RACELOG_URL}
      CROSSBAR_REALM: ${RACELOG_REALM}
      CROSSBAR_USER: ${RACELOG_USER}
      CROSSBAR_CREDENTIALS: ${CROSSBAR_BACKEND_TICKET}
      DB_URL: ${DB_URL}

    depends_on:
      db:
        condition: service_healthy
      iwr:
        condition: service_started

  # the frontend
  iracelog:
    image: ghcr.io/mpapenbr/iracelog-web:v0.18.3
    # only used for development
    ports:
      - ${IRACELOG_PORT:-8092}:80
    networks:
      - somenet

    environment:
      TZ: "Europe/Berlin"
    volumes:
      - ./config/iracelog/frontend.json:/usr/share/nginx/html/config.json

  # the graphql api service
  graphql:
    image: ghcr.io/mpapenbr/iracelog-graphql:v0.3.2
    ports:
      - "${GRAPHQL_PORT:-8093}:8080"
    networks:
      - somenet
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: "Europe/Berlin"
      DATABASE_URL: $DB_URL

  main-services:
    image: busybox
    command: sh -c "echo Starting services"
    depends_on:
      - db
      - iwr
      - db-migrate
      - ism
      - ias
      - iracelog
      - graphql

volumes:
  db-data:
  backup:


networks:
  somenet:
