
version: '3.1'

services:

  db:
    build: 
      context: postgres
      args: 
        postgres_tag: 13
    image: dev/iracelog-db:13
    restart: always
    volumes: 
      - db-data:/var/lib/postgresql/data
      - /var/local/dumps:/dumps
    env_file:
      - .env
    environment:
      TZ: "Europe/Berlin"
      
    networks: 
      - mynet
  
  crossbar:    
    image: crossbario/crossbar:cpy-amd64-21.2.1   
    restart: always 
    networks:
      - mynet    
    environment:
      TZ: "Europe/Berlin"
      VIRTUAL_PORT: 8080
      VIRTUAL_HOST: ${CROSSBAR_DOMAIN}
      LETSENCRYPT_HOST: ${CROSSBAR_DOMAIN}
      LETSENCRYPT_EMAIL: ${DOMAIN_OWNER_EMAIL}
      CROSSBAR_DATAPROVIDER_TICKET: ${CROSSBAR_DATAPROVIDER_TICKET}
      CROSSBAR_BACKEND_TICKET: ${CROSSBAR_BACKEND_TICKET}
      CROSSBAR_ADMIN_TICKET: ${CROSSBAR_ADMIN_TICKET}
    volumes:
      - $PWD/config/crossbar/cb-racelog.json:/node/.crossbar/config.json

  # iracelog-service-manager
  ism-manager:      
    image: ghcr.io/mpapenbr/iracelog-service-manager:v0.2.1
    restart: always
    networks: 
      - mynet
    env_file:       
      - .env
      - crossbar.env      
    environment:
      TZ: "Europe/Berlin"      
    command: "ism --check http://crossbar:8080/info manager"
    depends_on:
      - db
      - crossbar
  
  ism-archiver:      
    image: ghcr.io/mpapenbr/iracelog-service-manager:v0.2.1
    restart: always
    networks: 
      - mynet
    env_file:       
      - .env
      - crossbar.env      
    environment:
      TZ: "Europe/Berlin"      
    command: "ism --check http://crossbar:8080/info archiver"
    depends_on:
      - db
      - crossbar

  # iracelog-analysis-service
  ias:    
    image: ghcr.io/mpapenbr/iracelog-analysis-service:v0.1.1
    restart: always
    networks: 
      - mynet    
    environment:
      TZ: "Europe/Berlin"
      CROSSBAR_URL: ${RACELOG_URL}
      CROSSBAR_USER: ${RACELOG_USER}
      CROSSBAR_REALM: ${RACELOG_REALM}
      CROSSBAR_CREDENTIALS: ${RACELOG_PASSWORD}
      DB_URL: ${DB_URL}
    
    depends_on:
      - db
      - crossbar

  # the frontend
  iracelog:
    image: ghcr.io/mpapenbr/iracelog-web:v0.11.1    
    restart: always
    networks: 
      - mynet
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: ${FRONTEND_DOMAIN}
      LETSENCRYPT_HOST: ${FRONTEND_DOMAIN}
      LETSENCRYPT_EMAIL: ${DOMAIN_OWNER_EMAIL}
      TZ: "Europe/Berlin"
    volumes:
      - $PWD/config/iracelog/frontend.json:/usr/share/nginx/html/config.json
    
  
volumes:  
  db-data:
  backup:

networks:
  mynet:
  