
version: '3.1'

services:

  db:
    build: 
      context: postgres
      args: 
        postgres_tag: 13
    image: dev/iracelog-db:13
    # only used for development
    ports:
      - 5432:5432
    volumes: 
      - db-data:/var/lib/postgresql/data
      - /var/local/dumps:/dumps
    
    environment:
      TZ: "Europe/Berlin"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      DB_USER_NAME: ${DB_USER_NAME} 
      DB_USER_PASSWORD: ${DB_USER_PASSWORD} 
      
    networks: 
      - somenet
  
  crossbar:    
    image: crossbario/crossbar:cpy-amd64-21.2.1   
    # only used for development
    ports:
      - 8091:8080    
    networks:
      - somenet    

    environment:
      TZ: "Europe/Berlin"      
      CROSSBAR_DATAPROVIDER_TICKET: ${CROSSBAR_DATAPROVIDER_TICKET}
      CROSSBAR_BACKEND_TICKET: ${CROSSBAR_BACKEND_TICKET}
      CROSSBAR_ADMIN_TICKET: ${CROSSBAR_ADMIN_TICKET}
    volumes:
      - $PWD/config/crossbar/cb-racelog.json:/node/.crossbar/config.json

  # iracelog-service-manager
  ism-manager:      
    image: ghcr.io/mpapenbr/iracelog-service-manager:v0.2.2
    
    networks: 
      - somenet
      
    environment:
      TZ: "Europe/Berlin"
      RACELOG_URL: ${RACELOG_URL}
      RACELOG_REALM: ${RACELOG_REALM}
      RACELOG_USER: ${RACELOG_USER}
      RACELOG_PASSWORD: ${CROSSBAR_BACKEND_TICKET}
      DB_URL: postgresql://${DB_USER_NAME}:${DB_USER_PASSWORD}@db:5432/iracelog
      
    command: "ism --check http://crossbar:8080/info manager"
    depends_on:
      - db
      - crossbar
  
  ism-archiver:      
    image: ghcr.io/mpapenbr/iracelog-service-manager:v0.2.2
    
    networks: 
      - somenet
    
    environment:
      TZ: "Europe/Berlin"
      RACELOG_URL: ${RACELOG_URL}
      RACELOG_REALM: ${RACELOG_REALM}
      RACELOG_USER: ${RACELOG_USER}
      RACELOG_PASSWORD: ${CROSSBAR_BACKEND_TICKET}
      DB_URL: postgresql://${DB_USER_NAME}:${DB_USER_PASSWORD}@db:5432/iracelog

    command: "ism --check http://crossbar:8080/info archiver"
    depends_on:
      - db
      - crossbar

  # iracelog-analysis-service
  ias:    
    image: ghcr.io/mpapenbr/iracelog-analysis-service:v0.2.1    
    networks: 
      - somenet    
    
    environment:
      TZ: "Europe/Berlin"
      CROSSBAR_URL: ${RACELOG_URL}
      CROSSBAR_REALM: ${RACELOG_REALM}
      CROSSBAR_USER: ${RACELOG_USER}
      CROSSBAR_CREDENTIALS: ${CROSSBAR_BACKEND_TICKET}
      DB_URL: postgresql://${DB_USER_NAME}:${DB_USER_PASSWORD}@db:5432/iracelog
    
    depends_on:
      - db
      - crossbar

  # the frontend
  iracelog:
    image: ghcr.io/mpapenbr/iracelog-web:v0.16.3        
    # only used for development
    ports:
      - 8092:80
    networks: 
      - somenet
    
  
    environment:      
      TZ: "Europe/Berlin"
    volumes:
      - $PWD/config/iracelog/frontend.json:/usr/share/nginx/html/config.json

  # the graphql api service
  graphql:
    image: ghcr.io/mpapenbr/iracelog-graphql:v0.1.0
    ports:
      - "8093:8080"
    networks: 
      - somenet
    environment:
      TZ: "Europe/Berlin"
      DATABASE_URL: ${DB_URL}
    
  
  db-migrate:      
    
    image: ghcr.io/mpapenbr/iracelog-service-manager:v0.2.2    
    networks: 
      - somenet    
    environment:      
      DB_URL: postgresql://${DB_USER_NAME}:${DB_USER_PASSWORD}@db:5432/iracelog

    command: "./wait-for-it.sh -h db -p 5432 -s -- alembic -c src/iracelog_service_manager/db/alembic.ini  upgrade head"
    depends_on:
      - db
      
  main-services:
    image: busybox
    command: sh -c "Starting services"
    depends_on:
      - db
      - crossbar
      - ism-manager
      - ism-archiver
      - ias
      - iracelog
      - graphql


volumes:  
  db-data:
  backup:

networks:
  somenet:
  