apiVersion: v1
kind: Service
metadata:
  name: crossbar-service
  # namespace: iracelog
  labels:
    app: crossbar
spec:

  selector:
    app: crossbar
  ports:
    - protocol: TCP
      name: crossbar
      
      port: 8080
      targetPort: 8080
  
    

