apiVersion: v1
kind: Service
metadata:
  name: iracelog-frontend-service
  # namespace: iracelog
  labels:
    app: iracelog-app
spec:
  type: LoadBalancer
  selector:
    app: iracelog-app
  ports:
    - protocol: TCP
      name: frontend
      port: 8093
      targetPort: 80    
    

