apiVersion: v1
kind: Service
metadata:
  name: crossbar-service
  # namespace: iracelog
  labels:
    app: crossbar
spec:
  type: NodePort  
  selector:
    app: crossbar
  ports:
    - protocol: TCP
      name: crossbar
      nodePort: 30002
      port: 8080
      targetPort: 8080
  
    

