{{- if .Values.otlp.certmanager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: otel-collector-sidecar-client-cert  
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: iracelog-app
    app.kubernetes.io/component: otel-collector  
spec: {{- include "common.tplvalues.render" (dict "value" .Values.otlp.certmanager.spec "context" $) | nindent 2 }}  
{{- end }}