apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "iracelog-app.frontend.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/part-of: iracelog-app
    app.kubernetes.io/component: frontend
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  config.json: |
    {
      "grpc": {
          "url": {{ tpl .Values.grpcDomain . | quote }}
      },
      "graphql": {
          "url": {{ tpl .Values.graphql.url . | quote }}
      }

    }


