apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-crossbar
  namespace: {{ .Release.Namespace }}
  labels: &CrossbarDeploymentLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: crossbar
    
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: crossbar
  selector: *CrossbarDeploymentLabels
    

