apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-crossbar
  namespace: {{ .Release.Namespace }}
  labels: &CrossbarDeploymentLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: crossbar
  annotations: 
spec:
  selector:
    matchLabels: *CrossbarDeploymentLabels
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels: *CrossbarDeploymentLabels
        
    spec:
      containers:
      - name: crossbar
        image: "{{ .Values.crossbar.image }}:{{ .Values.crossbar.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef: 
              name: {{ .Release.Name }}-crossbar-secret
        volumeMounts:
        # this looks strange but it works to replace a config file 
        - name: config-volume
          mountPath: /node/.crossbar/config.json
          subPath: config.json
        resources:
          {{- toYaml .Values.crossbar.resources | nindent 12 }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-crossbar-config
