apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-crossbar-secret
  namespace: {{ .Values.namespace }}
  labels: 
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: crossbar
type: Opaque
data:
  CROSSBAR_ADMIN_TICKET: {{ .Values.crossbarAdminTicket | b64enc | quote }}
  CROSSBAR_DATAPROVIDER_TICKET: {{ .Values.crossbarDataProviderTicket | b64enc | quote }}
  CROSSBAR_BACKEND_TICKET: {{ .Values.crossbarBackendTicket | b64enc | quote }}
