apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-crossbar-secret
  namespace: {{ .Release.Namespace }}
  labels: 
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: crossbar
type: Opaque
data:
  CROSSBAR_ADMIN_TICKET: {{ .Values.crossbar.credentials.admin | b64enc | quote }}
  CROSSBAR_DATAPROVIDER_TICKET: {{ .Values.crossbar.credentials.dataProvider | b64enc | quote }}
  CROSSBAR_BACKEND_TICKET: {{ .Values.crossbar.credentials.backend | b64enc | quote }}
