apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-graphql
  namespace: {{ .Release.Namespace }}
  labels: &IracelogDeploymentLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: graphql
  annotations: 
spec:
  selector:
    matchLabels: *IracelogDeploymentLabels
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels: *IracelogDeploymentLabels
        
    spec:
      containers:
      - name: graphql
        image: {{ .Values.graphql.image }}:{{ .Values.graphqlVersion }}
        imagePullPolicy: IfNotPresent
        resources:
          {{- toYaml .Values.graphql.resources | nindent 12 }}
        ports:
          - containerPort: 8080
        envFrom:
          - secretRef:
                name: {{ .Release.Name }}-ism-secret
        env:
          - name: DATABASE_URL
            value: "postgresql://postgres:$(DB_USER_PASSWORD)@{{ .Release.Name }}-postgresql:5432/postgres"
