apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-graphql
  namespace: {{ .Release.Namespace }}
  labels: &IracelogDeploymentLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: graphql
    
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: graphql
  selector: *IracelogDeploymentLabels
    

