{{- if .Values.ingress.traefik.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingress-route-traefik
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:    
    - match: Host(`{{ tpl .Values.iracelogDomain . }}`) 
      kind: Rule
      services:
        - name: {{ .Release.Name }}-iracelog
          port: 80
    - match: Host(`{{ tpl .Values.crossbarDomain . }}`) 
      kind: Rule
      services:
        - name: {{ .Release.Name }}-crossbar
          port: 8080
    - match: Host(`{{ tpl .Values.graphqlDomain . }}`) 
      kind: Rule
      services:
        - name: {{ .Release.Name }}-graphql
          port: 8080
{{- end -}}