apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-iracelog-config
  namespace: {{ .Release.Namespace }}
  labels: 
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: iracelog

data:
  config.json: |
    {
      "crossbar": {
          "url": {{ tpl .Values.crossbarUrl . | quote }},
          "realm": "racelog"
      }
    }


