apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-iracelog
  namespace: {{ .Release.Namespace }}
  labels: &IracelogDeploymentLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: iracelog
    
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: iracelog
  selector: *IracelogDeploymentLabels
    

