apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ism-archiver
  namespace: {{ .Release.Namespace }}
  labels: &IsmArchiverDeploymentLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: ism-archiver
  annotations: 
spec:
  selector:
    matchLabels: *IsmArchiverDeploymentLabels
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels: *IsmArchiverDeploymentLabels
        
    spec:
      containers:
      - name: ism-manager
        image: ghcr.io/mpapenbr/iracelog-service-manager:{{ .Values.ismVersion }}
        imagePullPolicy: IfNotPresent
        
        envFrom:
          - secretRef:
                name: {{ .Release.Name }}-ism-secret
          - configMapRef:
                name: {{ .Release.Name }}-ism-config
        env:
          - name: DB_URL
            value: "postgresql://postgres:$(DB_USER_PASSWORD)@{{ .Release.Name }}-postgresql:5432/postgres"
        command: ["/bin/bash"]
        args: ["-c", "ism --check http://{{ .Release.Name }}-crossbar:8080/info archiver"]
      
        


        

        
