apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ism-config
  namespace: {{ .Values.namespace }}
  labels: 
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: ism

data:
  RACELOG_URL: ws://{{ .Release.Name }}-crossbar:8080/ws
  RACELOG_REALM: racelog
  RACELOG_USER: backend
  
