apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ism-secret
  namespace: {{ .Values.namespace }}
  labels: 
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: ism
type: Opaque
data:
  RACELOG_PASSWORD: {{ .Values.crossbarBackendTicket | b64enc | quote }}
  DB_USER_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  
  
