apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ism-config
  namespace: {{ .Release.Namespace }}
  labels: 
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: ism

data:
  ISM_URL: ws://{{ .Release.Name }}-iwr:8080
  ISM_REALM: racelog
  ISM_USER: backend
  
