apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-iwr
  namespace: {{ .Release.Namespace }}
  labels: &IwrDeploymentLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: iwr
  annotations: 
spec:
  selector:
    matchLabels: *IwrDeploymentLabels
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels: *IwrDeploymentLabels
        
    spec:
      containers:
      - name: iwr
        image: "{{ .Values.iwr.image }}:{{ .Values.iwrVersion }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef: 
              name: {{ .Release.Name }}-iwr-secret
        args: ["server"]
        
        
