apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-iwr-secret
  namespace: {{ .Release.Namespace }}
  labels: 
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: iwr
type: Opaque
data:
  ADMIN_TICKET: {{ .Values.crossbar.credentials.admin | b64enc | quote }}
  DATAPROVIDER_TICKET: {{ .Values.crossbar.credentials.dataProvider | b64enc | quote }}
  BACKEND_TICKET: {{ .Values.crossbar.credentials.backend | b64enc | quote }}
