apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-iwr
  namespace: {{ .Release.Namespace }}
  labels: &IwrLabels
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: iwr
    
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: iwr
  selector: *IwrLabels
    

