{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-postgres-secret
  namespace: {{ include "common.names.namespace" . }}
  labels:  
    {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4}}

type: Opaque
data:
  PGUSER: {{ "postgres" | b64enc | quote }}
  PGPASSWORD: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}  
{{- end -}}