apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql-secret
  namespace: {{ .Release.Namespace }}
  labels: 
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: postgres
type: Opaque
data:
  PGUSER: {{ "postgres" | b64enc | quote }}
  PGPASSWORD: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}  
  BLUBBER: {{ "something special" | b64enc | quote }}  
