apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "common.names.fullname" .}}-dummy
  labels:
    app: {{include "common.names.fullname" .}}
data:
  image: {{ include "common.images.image" ( dict "imageRoot" .Values.ism "global" .Values.global  "chart" .Chart ) }}
  imageOwn: {{ include "iracelog-app.images.image" ( dict "imageRoot" .Values.ism "global" .Values.global "imgVersion" .Values.ismVersion  "chart" .Chart ) }}
  irdomain: {{ tpl .Values.iracelogDomain . }}