apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iracelog

bases:
- ../base

configMapGenerator:
  - name: postgres-instance-config
    files:
    - 00-init-instance.sh=config/init-instance.sh
    - 01-updated-config.sh=config/update-config.sh

resources:
  # - postgres-test.yml  
  - postgres-pv.yml  
  # - persistentvolume.yml  
  - persistentvolumeclaim.yml  