apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iracelog-db-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
    