apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iracelog-db-claim
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
    limits:
      storage: 30Mi