apiVersion: v1
kind: PersistentVolume
metadata:
  name: iracelog-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 20Gi
    # storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv/data"

  